services:
  - type: web
    name: qwen-model-api
    env: python
    region: oregon
    plan: standard
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_TOKEN_READ
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
    autoDeploy: true
